import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftSidebar from "@/components/left-sidebar";
import RightSection from "@/components/right-section";
import SupabaseProvider from "./supabase-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-full flex items-center justify-center relative bg-black">
          <div className="w-full h-full flex xl:max-w-[140vh] relative">
            <LeftSidebar />
            <SupabaseProvider>{children}</SupabaseProvider>
            <RightSection />
          </div>
        </div>
      </body>
    </html>
  );
}
